name: flime
description: Android IME using flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  flutter: { sdk: flutter }
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  path_provider: ^2.0.9
  provider: ^6.0.1
  sqflite: ^2.0.2
  synchronized: ^3.0.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  ffigen: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test: { sdk: flutter }
  mobx_codegen: ^2.0.4
  pigeon: ^2.0.3
  sqflite_common_ffi: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/dict.db
    - assets/opencc/

  # fonts:

ffigen:
  name: 'Convert'
  description: 'Convert bindings.'
  output: './lib/api/native.dart'
  macros:
    exclude:
      - '.*'
  headers:
    entry-points:
      - './android/app/src/main/jni/native_convert.h'
