name: flime
description: Android IME using flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter: { sdk: flutter }
  flutter_mobx: ^2.0.3+2
  mobx: ^2.0.6+1
  provider: ^6.0.1
  sqflite: ^2.0.2
  synchronized: ^3.0.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test: { sdk: flutter }
  mobx_codegen: ^2.0.4
  pigeon: ^1.0.14
  sqflite_common_ffi: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/dict.db

  # fonts:
